Use controller util to get all workloads in the cluster
FairwindsOps/insights-plugins pull request #532
Opened 2021-11-16 15:59 UTC by makoscafee

## Description

## Checklist

* [ ] I have updated the CHANGELOG of any plugins updated
* [ ] I have updated the version file of any plugins updated
* [ ] I have added tests wherever appropriate
* [ ] I have labeled this PR with a label per plugin updated

2021-11-17 14:38 UTC, vitorvezani approved these changes
LGTM! Very generic, clean and concise 🔥

2021-11-22 15:56 UTC, ivanfetch-fw approved these changes
Wow - that's quite an improvement that replaces a lot of internal plugin code to track / map / determine individual "top controllers"  by our `GetAllTopControllers` function!

2021-11-22 19:32 UTC, rbren requested changes
Thanks Barnie! Love to see all that deleted code.

I think we need to change the container logic a bit though

2021-11-22 19:32 UTC, rbren commented on plugins/workloads/pkg/info.go
> +			for _, ctn := range pd.Spec.Containers {
I think we'll end up getting the same containers for each pod - we really just want to know what the container names are. 

You could use [`GetPodSpec`](https://github.com/FairwindsOps/controller-utils/blob/e9a28b6e43fcb89e2d304d5004566c8c5c383181/pkg/controller/pod.go#L20) to get the container names.

2021-11-23 16:51 UTC, rbren approved these changes

2021-11-23 17:27 UTC, merged